[project]
name = "pinchana-ytmusic"
version = "26.8.5"
description = "YouTube Music downloader for Pinchana"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pinchana-core",
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
]

[tool.uv.sources]
pinchana-core = { path = "../pinchana-core" }

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
